export const DEFAULT_RECIPE_ICON_PATH = '/icons/beer-types/001-beer.png';

export const RECIPE_ICON_OPTIONS = [
  { label: '001 beer', value: '/icons/beer-types/001-beer.png' },
  { label: '003 beer bottle', value: '/icons/beer-types/003-beer-bottle.png' },
  { label: '006 beer bottle 1', value: '/icons/beer-types/006-beer-bottle-1.png' },
  { label: '008 beer 1', value: '/icons/beer-types/008-beer-1.png' },
  { label: '009 beer 2', value: '/icons/beer-types/009-beer-2.png' },
  { label: '010 root beer', value: '/icons/beer-types/010-root-beer.png' },
  { label: '011 beer 3', value: '/icons/beer-types/011-beer-3.png' },
  { label: '013 pilsner', value: '/icons/beer-types/013-pilsner.png' },
  { label: '017 beer bottle 2', value: '/icons/beer-types/017-beer-bottle-2.png' },
  { label: '018 non alcoholic beer', value: '/icons/beer-types/018-non-alcoholic-beer.png' },
  { label: '019 beer 5', value: '/icons/beer-types/019-beer-5.png' },
  { label: '023 beer 7', value: '/icons/beer-types/023-beer-7.png' },
  { label: '024 beer 8', value: '/icons/beer-types/024-beer-8.png' },
  { label: '026 wooden mug', value: '/icons/beer-types/026-wooden-mug.png' },
  { label: '027 beer 10', value: '/icons/beer-types/027-beer-10.png' },
  { label: '029 beer 11', value: '/icons/beer-types/029-beer-11.png' },
  { label: '031 tulip glass', value: '/icons/beer-types/031-tulip-glass.png' },
  { label: '032 beer 13', value: '/icons/beer-types/032-beer-13.png' },
  { label: '035 green beer', value: '/icons/beer-types/035-green-beer.png' },
  { label: '036 beer 14', value: '/icons/beer-types/036-beer-14.png' },
  { label: '038 beer 16', value: '/icons/beer-types/038-beer-16.png' },
  { label: '042 shandy', value: '/icons/beer-types/042-shandy.png' },
  { label: '043 beer 19', value: '/icons/beer-types/043-beer-19.png' },
  { label: '044 pint of beer', value: '/icons/beer-types/044-pint-of-beer.png' },
  { label: '046 beer 20', value: '/icons/beer-types/046-beer-20.png' },
  { label: '047 beer mug', value: '/icons/beer-types/047-beer-mug.png' },
  { label: '048 mexican beer', value: '/icons/beer-types/048-mexican-beer.png' },
  { label: '049 beer can', value: '/icons/beer-types/049-beer-can.png' },
  { label: '050 beer mug 1', value: '/icons/beer-types/050-beer-mug-1.png' },
  { label: '052 beer mug 2', value: '/icons/beer-types/052-beer-mug-2.png' },
  { label: '053 beer mug 3', value: '/icons/beer-types/053-beer-mug-3.png' },
  { label: '054 beer mug 4', value: '/icons/beer-types/054-beer-mug-4.png' },
  { label: '055 beer mug 5', value: '/icons/beer-types/055-beer-mug-5.png' },
  { label: '056 beer mug 6', value: '/icons/beer-types/056-beer-mug-6.png' },
  { label: '057 beer mug 7', value: '/icons/beer-types/057-beer-mug-7.png' },
  { label: '058 beer mug 8', value: '/icons/beer-types/058-beer-mug-8.png' },
  { label: '059 beer mug 9', value: '/icons/beer-types/059-beer-mug-9.png' },
  { label: '060 beer mug 10', value: '/icons/beer-types/060-beer-mug-10.png' },
  { label: '061 beer mug 11', value: '/icons/beer-types/061-beer-mug-11.png' },
  { label: '062 beer mug 12', value: '/icons/beer-types/062-beer-mug-12.png' },
  { label: '063 beer mug 13', value: '/icons/beer-types/063-beer-mug-13.png' },
  { label: '064 beer 21', value: '/icons/beer-types/064-beer-21.png' },
  { label: '065 beer 22', value: '/icons/beer-types/065-beer-22.png' },
  { label: '066 beer 23', value: '/icons/beer-types/066-beer-23.png' },
  { label: '067 beer 24', value: '/icons/beer-types/067-beer-24.png' },
  { label: '068 beer 25', value: '/icons/beer-types/068-beer-25.png' },
  { label: '069 beer mug 14', value: '/icons/beer-types/069-beer-mug-14.png' },
  { label: '070 beer 26', value: '/icons/beer-types/070-beer-26.png' },
  { label: '072 beer 27', value: '/icons/beer-types/072-beer-27.png' },
  { label: '073 beer 28', value: '/icons/beer-types/073-beer-28.png' },
  { label: '074 beer 29', value: '/icons/beer-types/074-beer-29.png' },
  { label: '075 beer 30', value: '/icons/beer-types/075-beer-30.png' },
  { label: '076 beer 31', value: '/icons/beer-types/076-beer-31.png' },
  { label: '077 beer 32', value: '/icons/beer-types/077-beer-32.png' },
  { label: '078 beer mug 15', value: '/icons/beer-types/078-beer-mug-15.png' },
  { label: '079 beer mug 16', value: '/icons/beer-types/079-beer-mug-16.png' },
  { label: '080 pint of beer 1', value: '/icons/beer-types/080-pint-of-beer-1.png' },
  { label: '081 beers', value: '/icons/beer-types/081-beers.png' },
  { label: '082 beer 33', value: '/icons/beer-types/082-beer-33.png' },
  { label: '083 beer 34', value: '/icons/beer-types/083-beer-34.png' },
  { label: '084 beer 35', value: '/icons/beer-types/084-beer-35.png' },
  { label: '086 beer 36', value: '/icons/beer-types/086-beer-36.png' },
  { label: '087 beer can 1', value: '/icons/beer-types/087-beer-can-1.png' },
  { label: '088 beer 37', value: '/icons/beer-types/088-beer-37.png' },
  { label: '089 beer mug 17', value: '/icons/beer-types/089-beer-mug-17.png' },
  { label: '090 beer mug 18', value: '/icons/beer-types/090-beer-mug-18.png' },
  { label: '091 beer 38', value: '/icons/beer-types/091-beer-38.png' },
  { label: '092 beer 39', value: '/icons/beer-types/092-beer-39.png' },
  { label: '093 beer 40', value: '/icons/beer-types/093-beer-40.png' },
  { label: '094 beer 41', value: '/icons/beer-types/094-beer-41.png' },
  { label: '095 beer can 2', value: '/icons/beer-types/095-beer-can-2.png' },
  { label: '096 beer 42', value: '/icons/beer-types/096-beer-42.png' },
  { label: '097 beer 43', value: '/icons/beer-types/097-beer-43.png' },
  { label: '098 beer can 3', value: '/icons/beer-types/098-beer-can-3.png' },
  { label: '099 beer 44', value: '/icons/beer-types/099-beer-44.png' },
  { label: '100 beer 45', value: '/icons/beer-types/100-beer-45.png' },
  { label: '101 beer 46', value: '/icons/beer-types/101-beer-46.png' },
  { label: '102 beer 47', value: '/icons/beer-types/102-beer-47.png' },
  { label: '103 beer mug 19', value: '/icons/beer-types/103-beer-mug-19.png' },
  { label: '104 beer keg 2', value: '/icons/beer-types/104-beer-keg-2.png' },
  { label: '105 beer mug 20', value: '/icons/beer-types/105-beer-mug-20.png' },
  { label: '106 beer bottle 3', value: '/icons/beer-types/106-beer-bottle-3.png' },
  { label: '107 beer 48', value: '/icons/beer-types/107-beer-48.png' },
  { label: '108 beer 49', value: '/icons/beer-types/108-beer-49.png' },
  { label: '109 beer 50', value: '/icons/beer-types/109-beer-50.png' },
  { label: '110 beer 51', value: '/icons/beer-types/110-beer-51.png' },
  { label: '111 beer 52', value: '/icons/beer-types/111-beer-52.png' },
  { label: '112 beer 53', value: '/icons/beer-types/112-beer-53.png' },
  { label: '113 pint of beer 2', value: '/icons/beer-types/113-pint-of-beer-2.png' },
  { label: '114 beer 54', value: '/icons/beer-types/114-beer-54.png' },
  { label: '116 beer 55', value: '/icons/beer-types/116-beer-55.png' },
  { label: '117 beer 56', value: '/icons/beer-types/117-beer-56.png' },
  { label: '118 beer 57', value: '/icons/beer-types/118-beer-57.png' },
  { label: '119 beer 58', value: '/icons/beer-types/119-beer-58.png' },
  { label: '120 beer 59', value: '/icons/beer-types/120-beer-59.png' },
  { label: '121 beer 60', value: '/icons/beer-types/121-beer-60.png' },
  { label: '122 beer 61', value: '/icons/beer-types/122-beer-61.png' },
  { label: '123 beer 62', value: '/icons/beer-types/123-beer-62.png' },
  { label: '124 beer 63', value: '/icons/beer-types/124-beer-63.png' },
  { label: '125 beer 64', value: '/icons/beer-types/125-beer-64.png' },
  { label: '126 beer 65', value: '/icons/beer-types/126-beer-65.png' },
  { label: '127 beer 66', value: '/icons/beer-types/127-beer-66.png' },
  { label: '128 beer 67', value: '/icons/beer-types/128-beer-67.png' },
  { label: '129 beer 68', value: '/icons/beer-types/129-beer-68.png' },
  { label: '130 beer 69', value: '/icons/beer-types/130-beer-69.png' },
  { label: '131 black beer', value: '/icons/beer-types/131-black-beer.png' },
  { label: '132 poison', value: '/icons/beer-types/132-poison.png' },
  { label: '133 alcohol', value: '/icons/beer-types/133-alcohol.png' },
  { label: '136 coaster', value: '/icons/beer-types/136-coaster.png' },
  { label: '137 michelada', value: '/icons/beer-types/137-michelada.png' },
  { label: '143 cocktail', value: '/icons/beer-types/143-cocktail.png' },
  { label: '146 drinking', value: '/icons/beer-types/146-drinking.png' },
  { label: '149 wine glass', value: '/icons/beer-types/149-wine-glass.png' },
  { label: '150 wine', value: '/icons/beer-types/150-wine.png' },
  { label: '151 wine glass 1', value: '/icons/beer-types/151-wine-glass-1.png' },
  { label: '152 sparkling wine', value: '/icons/beer-types/152-sparkling-wine.png' },
  { label: '153 wine 1', value: '/icons/beer-types/153-wine-1.png' },
  { label: '154 wine glass 2', value: '/icons/beer-types/154-wine-glass-2.png' },
  { label: '155 wine bottle', value: '/icons/beer-types/155-wine-bottle.png' },
  { label: '156 mulled wine', value: '/icons/beer-types/156-mulled-wine.png' },
  { label: 'beer(1)', value: '/icons/beer-types/beer(1).png' },
  { label: 'beer', value: '/icons/beer-types/beer.png' },
  { label: 'beer1', value: '/icons/beer-types/beer1.png' },
  { label: 'beer2', value: '/icons/beer-types/beer2.png' },
  { label: 'beer3', value: '/icons/beer-types/beer3.png' },
  { label: 'beer4', value: '/icons/beer-types/beer4.png' },
  { label: 'beer bottle', value: '/icons/beer-types/beer-bottle.png' },
  { label: 'beers', value: '/icons/beer-types/beers.png' },
  { label: 'corn beer', value: '/icons/beer-types/corn-beer.png' },
];

export function resolveRecipeIconPath(iconPath) {
  return iconPath || DEFAULT_RECIPE_ICON_PATH;
}

export function ingredientCategoryIcon(category) {
  if (category === 'hops') return '/icons/002-hop.png';
  if (category === 'fermentable') return '/icons/140-bag.png';
  if (category === 'yeast') return '/icons/157-yeast.png';
  return '/icons/158-sprinkle.png';
}

export function ingredientCategoryLabel(t, category) {
  if (category === 'fermentable') return t('recipes.ingredient_category.fermentable');
  if (category === 'hops') return t('recipes.ingredient_category.hops');
  if (category === 'yeast') return t('recipes.ingredient_category.yeast');
  return t('recipes.ingredient_category.other');
}

export function ingredientCategoryOptions(t) {
  return [
    { label: t('recipes.ingredient_category.fermentable'), value: 'fermentable' },
    { label: t('recipes.ingredient_category.hops'), value: 'hops' },
    { label: t('recipes.ingredient_category.yeast'), value: 'yeast' },
    { label: t('recipes.ingredient_category.other'), value: 'other' },
  ];
}
